### ISSUE TITLE
"Mismatch between type and file name" warning not working with *.xaml.cs

### ISSUE THREAD

**Issue by ghost** [ulrichb/Roflcopter#1]
![image](https://user-images.githubusercontent.com/45970411/72968922-c539b800-3dc4-11ea-8361-26489ffa4f23.png)

Steps to reproduce:
- Create new WPF Application

**Comment by ulrichb** [comment]
Additional allowed file name postfixes can be configured in Options | Code Inspection | Mismatched file names.
