### ISSUE TITLE
Inaccurate Warning Message

### ISSUE THREAD

**Issue by Mike-E-angelo** [ulrichb/Roflcopter#2]
Greetings.  I wanted to report an issue that we've been tracking down in the JetBrains repository and they are saying it is due to this extension so wanted to pass the pain onto you. 😆

Here is the link for more details:
https://youtrack.jetbrains.com/issue/RSRP-478053#comment=27-3963217

Please let me know if there is any further information I can provide to assist and/or diagnose this issue for you. 👍

**Comment by ulrichb** [comment]
Hi. `.cshtml.cs` is not part of the default "allowed postfixes" configuration.

You can add at _Options | Code Inspection | Mismatched file names_.

**Comment by Mike-E-angelo** [comment]
Awesome.  THANK YOU VERY MUCH. :)
