### ISSUE TITLE
Compatibility with "Wave 242.0.0.0" missing

### ISSUE THREAD

**Issue by DarthSonic** [ulrichb/Roflcopter#3]
See image when trying to update ReSharper extensions:
![image](https://github.com/user-attachments/assets/37de4a9c-ca2e-4d5a-a366-d7afc8ee7d29)

**Comment by ulrichb** [comment]
This time it's more complicated to update the extension to R#/Rider 2024.2 SDK (on my side) ... I'm on it ...

**Comment by ulrichb** [comment]
Done and published to the marketplace.
